#!/usr/bin/env bash

declare -r api_host=127.10.10.20

main()
{
	local -r bookmark_json=${1?Manque le fichier JSON en paramètre du script test}
	curl -i -X POST -d@$bookmark_json "http://$api_host/bookmarks"
}

main "$@"
